### ISSUE TITLE
Logtail is not compatible with NextJS 15

### ISSUE THREAD

**Issue by mbre777** [logtail/logtail-nextjs#17]
npm error Could not resolve dependency:
npm error peer next@"^12.1.4 || ^13 || ^14" from @logtail/next@0.1.5
npm error node_modules/@logtail/next
npm error   @logtail/next@"^0.1.5" from the root project

logtail/next seems to be not compatible with NextJS 15

**Comment by logemann** [comment]
I have no problems running the lib with NextJS 15.0.3 installed it via yarn w/o problems.

**Comment by lazandrei19** [comment]
We just released version 0.1.6 which should support Next.js 15! 🎉
